### PR TITLE
World gallery: capstone project

### PR DESCRIPTION
**Pull request by AmanWorku**
## In this capstone project I have: 

- [x] Chose an API that is open and allows me to get numeric data out of it.
- [x] Followed design guidelines given by the curriculum.
- [x] Displayed all the countries on the home page found in the API.
- [x] Implemented a details page where it shows detailed information about the clicked country.
- [x] Added a search bar to search for a desired country from the list.
- [x] Implemented a function to return back to the home page using the `<` button.
- [x] Added a test for the pure function in the project.
- [x] Used `react router` for routing through the pages.
- [x] Added a professional `README` file.
- [x] Deployed the webpage on `render.com`. 

This is pretty much it, thank you.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @AmanWorku, you are missing the Key features section in your readme please add it 👍🏿

**Comment by prolajumokeoni** [comment]
Hi @AmanWorku 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  does not have the key features section in your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Nemwel-Boniface — CHANGES_REQUESTED** [review]
## Hello @AmanWorku       :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job working on your project so far! :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

**Because I am not able to highlight the pieces of code that needs changing, I will highlight it to you by visual aid**

- [ ] You have done a great job with your project layout. However, there is an arrow right that is currently in the project requirements which is supposed to act as the link to the details page fora specific country. KIndly include it.

**This is how your project looks like:**

image


**This is the desired design:**

image

- [ ] I have seen that your project only has one unit test. However, according to the project requirements, you are required to add unit tests for the following areas:
  - Create unit tests for pure functions in your Redux code.
  - Create integration tests for your application using the React Testing Library. 
image



_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmanWorku** [comment]
@Nemwel-Boniface Thank you so much. I'll do that accordingly. Have a good day.

**Review by DammyShittu — APPROVED** [review]
Hi @AmanWorku,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AmanWorku** [comment]
@DammyShittu Thank you so much, sir, have a great day.

**Pull request merged**
